{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "olm-catalog-datasource.fullname" . }}
  labels:
    {{- include "olm-catalog-datasource.labels" . | nindent 4 }}
  {{- if .Values.persistence.keep }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  accessModes: {{ toYaml .Values.persistence.accessModes | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- with .Values.persistence.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
