{{- if .Values.route.enabled }}
{{- if not (.Capabilities.APIVersions.Has "route.openshift.io/v1/Route") }}
{{- fail "route.enabled requires the OpenShift Route API" }}
{{- end }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "olm-catalog-datasource.fullname" . }}
  labels:
    {{- include "olm-catalog-datasource.labels" . | nindent 4 }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.route.host }}
  host: {{ . | quote }}
  {{- end }}
  to: {kind: Service, name: {{ include "olm-catalog-datasource.fullname" . }}}
  port: {targetPort: http}
  tls: {termination: edge, insecureEdgeTerminationPolicy: Redirect}
{{- end }}
