{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "olm-catalog-datasource.serviceAccountName" . }}
  labels:
    {{- include "olm-catalog-datasource.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
